name: Crystal

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        shards install --verbose
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec --verbose --error-trace --time -Dpreview_mt
